### ISSUE TITLE
关于函数代码本地与云端不一致问题

### ISSUE THREAD

**Issue by anycodes** [serverless-components/tencent-scf#13]
如果用户提交了部署请求，完成之后，本地会存储哈希值。下次用户再部署的时候会校验，如果校验一致则只升级配置。

针对这里我觉得应该加一层优化：
应该是升级代码+配置，只不过代码使用上一次存储到cos的代码。

之所以这么做的原因是：如果用户部署完成，把线上函数删了，再重新部署，他会只修改配置，此时函数不存在，会报错。

**Comment by yugasun** [comment]
@anycodes 大佬说的我很赞同，但是对于用户去控制台手动删除函数的操作，做不做考虑兼容，这个待会商榷一下

**Comment by anycodes** [comment]
@yugasun 我理解，我们做的这个功能是为了提升非代码变更时候的部署速度，而不是说功能变更，因为之前这样操作是可以的，我觉得这个算是相对之前的不兼容变更。
另外一个问题：如果scf默认打包的时候不排除.serverless，可能在某些情况导致hash这一'失效'，这里可能也要看一下。
