### ISSUE TITLE
COS usage is growing w/o control when we deploy cloud functions via COS

### ISSUE THREAD

**Issue by liuwenchao** [serverless-components/tencent-scf#14]
用COS来部署云函数一段时间后，发现COS会保留所有发布的版本，随着版本的迭代COS的用量只增不减，这个实际上没有太大价值，现实场景里面我们只需要保留特定的版本即可。这个是否可以通过COS部署方式里面的一些配置来实现。

更深一个层次的思考是用户是否真的需要管理COS，作为云函数的一个部署方式，如果能做到用户在部署的地方只需配置一下，可以下载对应版本文件，在一个地方把需要关心的事情能完成，产品可用性会比现在把COS功能暴露给用户自己管理好很多。

After using COS to deploy cloud functions a while, we figured the COS usage is growing w/o control. This actually has little value, in the real case we just need to keep certain versions. Is it possible to extract this into a configuration?

A further question is: Does user really need to manage COS? It would increase the usability of the product if user can turn COS on in deployment configuration, download the specific version online as needed, in the same place.

**Comment by tinafangkunding** [comment]
您好，感谢反馈，我们当前讨论的结论是会在近期支持 COS 的默认生命周期能力，默认回收 10 天之前的代码包。并且计划后续同时支持基于版本/时间上的清理策略
@anycodes @yugasun

**Comment by anycodes** [comment]
已经增加了生命周配置，同时开放自定义cos部署
