### ISSUE TITLE
配置了函数的namespace后，APIGW触发器中如何配置namespace呢？

### ISSUE THREAD

**Issue by sdlyfjx** [serverless-components/tencent-scf#23]
找到了。根据API网关的接口文档，猜测后发现，在function中与isItegratedResponse同级加入functionNamespace字段即可生效。

建议：默认使用scf的output进行配置，这样用户只需要配置scf上的namespace这里就可以统一了。

**Comment by yugasun** [comment]
@sdlyfjx 当前就是这么设计的，scf配置的 apigw触发器，会默认使用 scf 的 namespace。

**Comment by sdlyfjx** [comment]
@yugasun 哦？已经修复了吗？之前提issues的时候因为没有这个机制，所以才找了半天手动配置的参数来着
