### ISSUE TITLE
SCF组件中如何使用APIGW的mock模式呢？

### ISSUE THREAD

**Issue by sdlyfjx** [serverless-components/tencent-scf#24]
按照APIGW的文档尝试修改了一下yml但是没有成功。没有看到有哪个地方显示可以将后端配置为mock而不是scf的模式。还请完善一下文档或者是否有这个功能？挺需要的。。。

**Comment by yugasun** [comment]
@sdlyfjx 最新版 SCF 已支持，可以尝试体验下

**Comment by sdlyfjx** [comment]
哟西~  暂时用APIGW的component解决的。麻烦更新下介个文档哇

**Comment by tinafangkunding** [comment]
get, 网关的文档我们更新一下

**Comment by tinafangkunding** [comment]
https://github.com/serverless-components/tencent-apigateway/blob/v2/docs/configure.md 网关的也更新了 @sdlyfjx 
![image](https://user-images.githubusercontent.com/26135229/86095884-1f157b00-bae5-11ea-8277-819b2ab9a60d.png)
