### ISSUE TITLE
golang scf中的codeUri如何配置

### ISSUE THREAD

**Issue by hjiog** [serverless-components/tencent-scf#25]
如果运行环境是golang，代码需要提前编译吗？codeUri中的路径是放代码的路径还是编译后的路径？

**Comment by hjiog** [comment]
![image](https://user-images.githubusercontent.com/42141272/84106872-d8d17c80-aa4e-11ea-8ff4-0174634f2782.png)
试了很多次都是报这个错误，能否给个golang的例子？拜谢

**Comment by tinafangkunding** [comment]
是需要提前编译的哈
