### ISSUE TITLE
config文件缺少namespace的配置

### ISSUE THREAD

**Issue by ycp424c** [serverless-components/tencent-scf#4]
现在只能部署到default namespace下面，项目需要部署到不同的namespace

**Comment by pmuens** [comment]
Hey @ycp424c thanks for opening :+1:

I've just created #5 which should cover this use case.

**Comment by anycodes** [comment]
非常感谢您这里提出的意见，目前Serverless Framework暂时只支持default。是否会支持更多的命名空间，可能还要确定一下。

**Comment by anycodes** [comment]
@tinafangkunding cc
