### ISSUE TITLE
【Bug】本地 bootstrap 文件拥有x执行权限，通过 sls deploy 后，云上无x执行

### ISSUE THREAD

**Issue by RayWangQvQ** [serverless-components/tencent-scf#60]
本地环境：基于win10的wsl2安装的ubuntu

本地权限：
![image](https://user-images.githubusercontent.com/31154238/117529704-9c662200-b00b-11eb-981e-07de81fc3507.png)

使用 sls deploy 部署后：
![image](https://user-images.githubusercontent.com/31154238/117529490-66746e00-b00a-11eb-8c68-fe37b8e01450.png)

另外，如果是本地压缩好，然后手动上传zip，权限是正常的。

请问是否是我遗漏了什么？是否有解决的办法？

谢谢。

**Comment by timqian** [comment]
你安装的 serverless 版本是多少？这个问题在老版本的 serverless 中出现过，最新版应该是修复了的。

```bash
$ sls -v

Framework Core: 2.37.0
Plugin: 4.5.3
SDK: 4.2.2
Components: 3.9.0
```

**Comment by RayWangQvQ** [comment]
![image](https://user-images.githubusercontent.com/31154238/117530830-dd613500-b011-11eb-89f8-b3f43a2ebe50.png)

我是先在 win10 上部署的，发现上传上去的没有x执行权限。

然后想到之前手动上传zip包的时候，用 windows 压缩确实会存在缺少x权限的问题，当时通过在 ubuntu 压缩后再手动上传 zip 解决了。

所以我就又在 ubuntu 里装了 Serverless Framework，但是这次问题依然存在。

**Comment by RayWangQvQ** [comment]
有了新的进展：

我尝试在 yml 里重新命名了组件名称和函数名称后，也就是执行全新部署，在新的函数应用里权限正常了。

这样看的话，是在第一次部署后（没有x权限），后面再次执行更新部署，不会将变更的权限更新上去。

**Comment by timqian** [comment]
为了加速部署，serverless 默认会缓存文件，如果文件内容没有改变的话不会重新上传。可以使用 `sls deploy --force` 来忽略先前缓存的文件

**Comment by RayWangQvQ** [comment]
果然是有缓存，`sls deploy --force` 成功解决了，谢谢！
