### ISSUE TITLE
可以支持读取全局配置吗？

### ISSUE THREAD

**Issue by deancn** [serverless-components/tencent-scf#64]
当前读取配置 `.env`,  如果项目比较多不便于管理。

可以支持优先读取全局配置文件吗？
比如 `./config/sls/tencent.env`， 如果不存在再读取当前目录。

**Comment by AprilJC** [comment]
您好，目前已经支持全局变量配置权限信息，通过 `sls credentials` 指令，即可配置全局变量，部署时，如果项目根目录下没有 `.env` 文件，会自动读取全局变量里的配置信息
![](https://main.qcloudimg.com/raw/41fa404cb139e9a5bede582584bdc6a2.png)

**Comment by ole3021** [comment]
目前在 Serverless CLI 3.9.0 以上的版本中已经加入了，全局身份授权管理的功能，相关的说明可以参考我们的 更新日志
https://github.com/serverless/serverless-tencent/discussions/4#discussioncomment-638680

稍后我们也会在帮助文档整理完成之后，在帮助文档中更新。 如果对于使用有任何疑问或者问题，也欢迎到 [中文讨论社区](https://github.com/serverless/serverless-tencent/discussions)中讨论。

**Comment by deancn** [comment]
Platform:  Apple M1

执行
```bash
sls credentials set  -i XXX  -k XXX
```
 后 credential保存在  ~/.serverless/tencent/credentials.

但是如果当前目录没有 `.env` 文件会报错。


![image](https://user-images.githubusercontent.com/1617384/119289954-38d02b80-bc7e-11eb-9a82-11cb043ce367.png)

**Comment by ole3021** [comment]
这里报错是因为程序判定你这里使用的是 国际版本的serverless,并不是 腾讯云的serverless, 建议添加环境变量 `SERVERLESS_PLATFORM_VENDOR=tencent` 后重试. @deancn  如果添加后还有问题, 欢迎到 https://github.com/serverless/serverless-tencent/issues/new/choose  提交BUG反馈

**Comment by deancn** [comment]
@ole3021  好的，非常感谢。
