### ISSUE TITLE
建议在serverless.yml中增加配置'重试次数'选项

### ISSUE THREAD

**Issue by Ca11back** [serverless-components/tencent-scf#71]
函数配置->异步调用->重试次数 选项可否在serverless.yml中增加配置支持

**Comment by yugasun** [comment]
已支持，参考文档 https://github.com/serverless-components/tencent-scf/blob/master/docs/configure.md

```yaml
msgTTL: 21600 # 消息保留时间，单位秒
retryNum: 2 # 重试次数
```
